//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 前のページに戻る 的本地化字符串。
        /// </summary>
        public static string Common_Button_Back {
            get {
                return ResourceManager.GetString("Common_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 キャンセル 的本地化字符串。
        /// </summary>
        public static string Common_Button_Cancel {
            get {
                return ResourceManager.GetString("Common_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閉じる 的本地化字符串。
        /// </summary>
        public static string Common_Button_Close {
            get {
                return ResourceManager.GetString("Common_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次のページに進む 的本地化字符串。
        /// </summary>
        public static string Common_Button_Forward {
            get {
                return ResourceManager.GetString("Common_Button_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Common_Button_OK {
            get {
                return ResourceManager.GetString("Common_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ページを更新する 的本地化字符串。
        /// </summary>
        public static string Common_Button_Refresh {
            get {
                return ResourceManager.GetString("Common_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 既定値に戻す 的本地化字符串。
        /// </summary>
        public static string Common_Button_Reset2Default {
            get {
                return ResourceManager.GetString("Common_Button_Reset2Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再試行 的本地化字符串。
        /// </summary>
        public static string Common_Button_Retry {
            get {
                return ResourceManager.GetString("Common_Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常に確認する 的本地化字符串。
        /// </summary>
        public static string Common_Confirmation_Always {
            get {
                return ResourceManager.GetString("Common_Confirmation_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確認しない 的本地化字符串。
        /// </summary>
        public static string Common_Confirmation_Disable {
            get {
                return ResourceManager.GetString("Common_Confirmation_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃中のみ確認する 的本地化字符串。
        /// </summary>
        public static string Common_Confirmation_InSortie {
            get {
                return ResourceManager.GetString("Common_Confirmation_InSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 既定値 的本地化字符串。
        /// </summary>
        public static string Common_DefaultValue {
            get {
                return ResourceManager.GetString("Common_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※近日実装予定 的本地化字符串。
        /// </summary>
        public static string Common_Implement_Oncoming {
            get {
                return ResourceManager.GetString("Common_Implement_Oncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL を入力し、Enter キーで移動します。 的本地化字符串。
        /// </summary>
        public static string Common_NavigateCommand {
            get {
                return ResourceManager.GetString("Common_NavigateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用しない 的本地化字符串。
        /// </summary>
        public static string Common_Needless {
            get {
                return ResourceManager.GetString("Common_Needless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 結果なし 的本地化字符串。
        /// </summary>
        public static string Common_NoResult {
            get {
                return ResourceManager.GetString("Common_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知しない 的本地化字符串。
        /// </summary>
        public static string Common_Notifications_Disable {
            get {
                return ResourceManager.GetString("Common_Notifications_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (未実装) 的本地化字符串。
        /// </summary>
        public static string Common_Notifications_NotImplemented {
            get {
                return ResourceManager.GetString("Common_Notifications_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知設定 的本地化字符串。
        /// </summary>
        public static string Common_Notifications_Title {
            get {
                return ResourceManager.GetString("Common_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Windows 8 以降) 的本地化字符串。
        /// </summary>
        public static string Common_Notifications_Windows8 {
            get {
                return ResourceManager.GetString("Common_Notifications_Windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦娘 的本地化字符串。
        /// </summary>
        public static string Common_ShipGirl {
            get {
                return ResourceManager.GetString("Common_ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 データ 的本地化字符串。
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 これはテスト通知です。 的本地化字符串。
        /// </summary>
        public static string Debug_NotificationMessage {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テスト 的本地化字符串。
        /// </summary>
        public static string Debug_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造ドック 的本地化字符串。
        /// </summary>
        public static string Dockyard {
            get {
                return ResourceManager.GetString("Dockyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成！ 的本地化字符串。
        /// </summary>
        public static string Dockyard_Complete {
            get {
                return ResourceManager.GetString("Dockyard_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造中の艦名をネタバレする 的本地化字符串。
        /// </summary>
        public static string Dockyard_Display_Reveal {
            get {
                return ResourceManager.GetString("Dockyard_Display_Reveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示設定 的本地化字符串。
        /// </summary>
        public static string Dockyard_Display_Title {
            get {
                return ResourceManager.GetString("Dockyard_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ロックされています 的本地化字符串。
        /// </summary>
        public static string Dockyard_Locked {
            get {
                return ResourceManager.GetString("Dockyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工廠第 {0} ドックでの{1}の建造が完了しました。 的本地化字符串。
        /// </summary>
        public static string Dockyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造完了 的本地化字符串。
        /// </summary>
        public static string Dockyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造完了時に通知を表示する 的本地化字符串。
        /// </summary>
        public static string Dockyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ドックごとに個別に設定する 的本地化字符串。
        /// </summary>
        public static string Dockyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造中の艦 的本地化字符串。
        /// </summary>
        public static string Dockyard_ShipName {
            get {
                return ResourceManager.GetString("Dockyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成時刻 的本地化字符串。
        /// </summary>
        public static string Dockyard_TimeComplete {
            get {
                return ResourceManager.GetString("Dockyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造完了まで 的本地化字符串。
        /// </summary>
        public static string Dockyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Dockyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未使用 的本地化字符串。
        /// </summary>
        public static string Dockyard_Unused {
            get {
                return ResourceManager.GetString("Dockyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Equipment_DamageControl {
            get {
                return ResourceManager.GetString("Equipment_DamageControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「提督業も忙しい！」 を終了します。よろしいですか？ 的本地化字符串。
        /// </summary>
        public static string ExitDialog_Description {
            get {
                return ResourceManager.GetString("ExitDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 終了確認 的本地化字符串。
        /// </summary>
        public static string ExitDialog_Title {
            get {
                return ResourceManager.GetString("ExitDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征 的本地化字符串。
        /// </summary>
        public static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征に出ていません。 的本地化字符串。
        /// </summary>
        public static string Expedition_NoExpedition {
            get {
                return ResourceManager.GetString("Expedition_NoExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「{0}」が遠征から帰投しました。 的本地化字符串。
        /// </summary>
        public static string Expedition_NotificationMessage {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征完了 的本地化字符串。
        /// </summary>
        public static string Expedition_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征帰投時に通知を表示する 的本地化字符串。
        /// </summary>
        public static string Expedition_Notifications_Enable {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊ごとに個別に設定する 的本地化字符串。
        /// </summary>
        public static string Expedition_Notifications_Individual {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 終了時刻 的本地化字符串。
        /// </summary>
        public static string Expedition_TimeComplete {
            get {
                return ResourceManager.GetString("Expedition_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊帰投まで 的本地化字符串。
        /// </summary>
        public static string Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊 的本地化字符串。
        /// </summary>
        public static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制空戦力 的本地化字符串。
        /// </summary>
        public static string Fleets_AirSuperiorityPotential {
            get {
                return ResourceManager.GetString("Fleets_AirSuperiorityPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対潜 的本地化字符串。
        /// </summary>
        public static string Fleets_ASW {
            get {
                return ResourceManager.GetString("Fleets_ASW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均 的本地化字符串。
        /// </summary>
        public static string Fleets_Average {
            get {
                return ResourceManager.GetString("Fleets_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火力 的本地化字符串。
        /// </summary>
        public static string Fleets_Karyoku {
            get {
                return ResourceManager.GetString("Fleets_Karyoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レベル 的本地化字符串。
        /// </summary>
        public static string Fleets_Level {
            get {
                return ResourceManager.GetString("Fleets_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高速艦隊 的本地化字符串。
        /// </summary>
        public static string Fleets_Speed_Fast {
            get {
                return ResourceManager.GetString("Fleets_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低速艦隊 的本地化字符串。
        /// </summary>
        public static string Fleets_Speed_Slow {
            get {
                return ResourceManager.GetString("Fleets_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合計 的本地化字符串。
        /// </summary>
        public static string Fleets_Total {
            get {
                return ResourceManager.GetString("Fleets_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索敵能力 的本地化字符串。
        /// </summary>
        public static string Fleets_ViewRange {
            get {
                return ResourceManager.GetString("Fleets_ViewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 司令部 的本地化字符串。
        /// </summary>
        public static string Homeport_FleetHQ {
            get {
                return ResourceManager.GetString("Homeport_FleetHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高速建造材: 的本地化字符串。
        /// </summary>
        public static string Homeport_InstantBuild {
            get {
                return ResourceManager.GetString("Homeport_InstantBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高速修復材: 的本地化字符串。
        /// </summary>
        public static string Homeport_InstantRepair {
            get {
                return ResourceManager.GetString("Homeport_InstantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保有装備: 的本地化字符串。
        /// </summary>
        public static string Homeport_NoOfEquipment {
            get {
                return ResourceManager.GetString("Homeport_NoOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属艦娘: 的本地化字符串。
        /// </summary>
        public static string Homeport_NoOfShips {
            get {
                return ResourceManager.GetString("Homeport_NoOfShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 総合 的本地化字符串。
        /// </summary>
        public static string IntegratedView {
            get {
                return ResourceManager.GetString("IntegratedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 この艦隊は遠征中です。 的本地化字符串。
        /// </summary>
        public static string MessageBar_Expedition {
            get {
                return ResourceManager.GetString("MessageBar_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  完了時刻: 的本地化字符串。
        /// </summary>
        public static string MessageBar_Expedition_TimeCompletion {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  帰投まで: 的本地化字符串。
        /// </summary>
        public static string MessageBar_Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に入渠中の艦娘がいます。 完了時刻: {0:MM/dd HH\:mm} 完了まで: {1}:{2:mm\:ss} 的本地化字符串。
        /// </summary>
        public static string MessageBar_Repairing {
            get {
                return ResourceManager.GetString("MessageBar_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に入渠中の艦娘がいます。 的本地化字符串。
        /// </summary>
        public static string MessageBar_Repairing_Null {
            get {
                return ResourceManager.GetString("MessageBar_Repairing_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労中の艦娘 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_BadCondition {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_BadCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に{0}がいます。 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_CanNotReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanNotReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃可能！ 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_CanReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未補給の艦娘 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_LackForResources {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_LackForResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再出撃までの目安:  的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_Remaining {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ・ 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_Separator {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中破以上の艦娘 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_Wounded {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Wounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 読み込みに失敗したプラグイン 的本地化字符串。
        /// </summary>
        public static string Plugin_Failed {
            get {
                return ResourceManager.GetString("Plugin_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下のプラグインは、読み込みに失敗し動作していません。発生したエラーの詳細を確認できます。 的本地化字符串。
        /// </summary>
        public static string Plugin_Failed_Description {
            get {
                return ResourceManager.GetString("Plugin_Failed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プラグインからの通知 的本地化字符串。
        /// </summary>
        public static string Plugin_Function_Request2Notify {
            get {
                return ResourceManager.GetString("Plugin_Function_Request2Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タスク バー インジケーター 的本地化字符串。
        /// </summary>
        public static string Plugin_Function_TaskbarIndicator {
            get {
                return ResourceManager.GetString("Plugin_Function_TaskbarIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ツール表示 的本地化字符串。
        /// </summary>
        public static string Plugin_Function_Tool {
            get {
                return ResourceManager.GetString("Plugin_Function_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 読み込み済みのプラグイン 的本地化字符串。
        /// </summary>
        public static string Plugin_Loaded {
            get {
                return ResourceManager.GetString("Plugin_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下のプラグインが読み込まれています。各プラグインの設定を変更できます。 的本地化字符串。
        /// </summary>
        public static string Plugin_Loaded_Description {
            get {
                return ResourceManager.GetString("Plugin_Loaded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※設定を変更したら [再試行] ボタンを押してください。 的本地化字符串。
        /// </summary>
        public static string ProxyBootstrapper_Set2Retry {
            get {
                return ResourceManager.GetString("ProxyBootstrapper_Set2Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任務 的本地化字符串。
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在遂行中の任務 的本地化字符串。
        /// </summary>
        public static string Quests_CurrentQuestList {
            get {
                return ResourceManager.GetString("Quests_CurrentQuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 デイリー任務 的本地化字符串。
        /// </summary>
        public static string Quests_Daily {
            get {
                return ResourceManager.GetString("Quests_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※進捗状況 (50 %, 80 %) はゲーム内の表示と同じです。敵艦隊の撃破数や遠征の成功回数のカウント等は行っていません。 的本地化字符串。
        /// </summary>
        public static string Quests_Notice {
            get {
                return ResourceManager.GetString("Quests_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ゲーム内で [任務 (クエスト)] 画面を開いて、任務一覧を取得してください。 的本地化字符串。
        /// </summary>
        public static string Quests_Untaken {
            get {
                return ResourceManager.GetString("Quests_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィークリー任務 的本地化字符串。
        /// </summary>
        public static string Quests_Weekly {
            get {
                return ResourceManager.GetString("Quests_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠ドック 的本地化字符串。
        /// </summary>
        public static string Repairyard {
            get {
                return ResourceManager.GetString("Repairyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ロックされています 的本地化字符串。
        /// </summary>
        public static string Repairyard_Locked {
            get {
                return ResourceManager.GetString("Repairyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠第 {0} ドックでの「{1}」の整備が完了しました。 的本地化字符串。
        /// </summary>
        public static string Repairyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整備完了 的本地化字符串。
        /// </summary>
        public static string Repairyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整備完了時に通知を表示する 的本地化字符串。
        /// </summary>
        public static string Repairyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ドックごとに個別に設定する 的本地化字符串。
        /// </summary>
        public static string Repairyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠中の艦 的本地化字符串。
        /// </summary>
        public static string Repairyard_ShipName {
            get {
                return ResourceManager.GetString("Repairyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完了時刻 的本地化字符串。
        /// </summary>
        public static string Repairyard_TimeComplete {
            get {
                return ResourceManager.GetString("Repairyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整備完了まで 的本地化字符串。
        /// </summary>
        public static string Repairyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Repairyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未使用 的本地化字符串。
        /// </summary>
        public static string Reparyard_Unused {
            get {
                return ResourceManager.GetString("Reparyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「{0}」の全艦娘の疲労が回復しました。 的本地化字符串。
        /// </summary>
        public static string ReSortie_NotificationMessage {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労回復完了 的本地化字符串。
        /// </summary>
        public static string ReSortie_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショットの保存に失敗しました:  的本地化字符串。
        /// </summary>
        public static string Screenshot_Failed {
            get {
                return ResourceManager.GetString("Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショットを保存しました:  的本地化字符串。
        /// </summary>
        public static string Screenshot_Saved {
            get {
                return ResourceManager.GetString("Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設定 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザー操作 的本地化字符串。
        /// </summary>
        public static string Settings_BrowserControl {
            get {
                return ResourceManager.GetString("Settings_BrowserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ズーム倍率を 100 % に戻す 的本地化字符串。
        /// </summary>
        public static string Settings_BrowserControl_ClearZoomFactorButton {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_ClearZoomFactorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (表示) 的本地化字符串。
        /// </summary>
        public static string Settings_BrowserControl_Display {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※ゲームのページから移動します。ご注意ください 的本地化字符串。
        /// </summary>
        public static string Settings_BrowserControl_Notice {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示設定 的本地化字符串。
        /// </summary>
        public static string Settings_Display {
            get {
                return ResourceManager.GetString("Settings_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アプリケーション終了時の確認動作 的本地化字符串。
        /// </summary>
        public static string Settings_Display_ExitConfirmation {
            get {
                return ResourceManager.GetString("Settings_Display_ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 言語 的本地化字符串。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ローカル待ち受けポート設定 的本地化字符串。
        /// </summary>
        public static string Settings_LocalListeningPort {
            get {
                return ResourceManager.GetString("Settings_LocalListeningPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待ち受けポートを変更する 的本地化字符串。
        /// </summary>
        public static string Settings_LocalProxy_IsEnabled {
            get {
                return ResourceManager.GetString("Settings_LocalProxy_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログ 的本地化字符串。
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ドロップ・建造・開発ログを記録する 的本地化字符串。
        /// </summary>
        public static string Settings_Logging_Enable {
            get {
                return ResourceManager.GetString("Settings_Logging_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信設定 的本地化字符串。
        /// </summary>
        public static string Settings_Network {
            get {
                return ResourceManager.GetString("Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 動作設定 的本地化字符串。
        /// </summary>
        public static string Settings_Operation {
            get {
                return ResourceManager.GetString("Settings_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊ステータス 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_FleetsStatus {
            get {
                return ResourceManager.GetString("Settings_Operation_FleetsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 その他 的本地化字符串。
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プラグイン 的本地化字符串。
        /// </summary>
        public static string Settings_Plugin {
            get {
                return ResourceManager.GetString("Settings_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロキシ設定 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy {
            get {
                return ResourceManager.GetString("Settings_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロキシ サーバーを使用しない 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Disable {
            get {
                return ResourceManager.GetString("Settings_Proxy_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全てのプロトコルでプロキシ サーバーを中継せずに直接サーバーと通信を行います。 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Disable_Description {
            get {
                return ResourceManager.GetString("Settings_Proxy_Disable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロキシ サーバーを指定する 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Enable {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定したプロキシ サーバーを中継して通信を行います。 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Enable_Description1 {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 サーバーをホスト名で指定した場合、動作が遅くなることがあるため、IP アドレスでの指定を推奨します。 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Enable_Description2 {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全てのプロトコルでこのプロキシ サーバーを使用する 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Enable_ForAllProtocols {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_ForAllProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 サーバー 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Host {
            get {
                return ResourceManager.GetString("Settings_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internet Explorer のプロキシ設定を使用する 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_IESettings {
            get {
                return ResourceManager.GetString("Settings_Proxy_IESettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「インターネット オプション」の設定を用いて通信を行います。 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_IESettings_Description {
            get {
                return ResourceManager.GetString("Settings_Proxy_IESettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ポート 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Port {
            get {
                return ResourceManager.GetString("Settings_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※反映にはアプリケーションの再起動が必要です。 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Restart2Apply {
            get {
                return ResourceManager.GetString("Settings_Proxy_Restart2Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショット 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot {
            get {
                return ResourceManager.GetString("Settings_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_OpenButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショットの保存先を指定 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_Title {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存先 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存先フォルダーのパス 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Prompt {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画像形式 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_ImageFormat_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_ImageFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フォルダーを開く 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_OpenFolderButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ユーザー スタイル シート 的本地化字符串。
        /// </summary>
        public static string Settings_StyleSheets {
            get {
                return ResourceManager.GetString("Settings_StyleSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タスク バー設定 的本地化字符串。
        /// </summary>
        public static string Settings_Taskbar {
            get {
                return ResourceManager.GetString("Settings_Taskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 インジケーターの動作 的本地化字符串。
        /// </summary>
        public static string Settings_Taskbar_ProgressIndicator {
            get {
                return ResourceManager.GetString("Settings_Taskbar_ProgressIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 バージョン情報 的本地化字符串。
        /// </summary>
        public static string Settings_VersionInfo {
            get {
                return ResourceManager.GetString("Settings_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ設定 的本地化字符串。
        /// </summary>
        public static string Settings_Window {
            get {
                return ResourceManager.GetString("Settings_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウを常に最前面に表示する 的本地化字符串。
        /// </summary>
        public static string Settings_Window_TopMost {
            get {
                return ResourceManager.GetString("Settings_Window_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ操作 的本地化字符串。
        /// </summary>
        public static string Settings_WindowControl {
            get {
                return ResourceManager.GetString("Settings_WindowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウをモニターの左端に寄せる 的本地化字符串。
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 インチタブレット (800 x 1280) 用 的本地化字符串。
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton_Sub {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ レイアウト 的本地化字符串。
        /// </summary>
        public static string Settings_WindowLayout {
            get {
                return ResourceManager.GetString("Settings_WindowLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 マルチ ウィンドウ 的本地化字符串。
        /// </summary>
        public static string Settings_WindowLayout_MultiWindow {
            get {
                return ResourceManager.GetString("Settings_WindowLayout_MultiWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 シングル ウィンドウ 的本地化字符串。
        /// </summary>
        public static string Settings_WindowLayout_SingleWindow {
            get {
                return ResourceManager.GetString("Settings_WindowLayout_SingleWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次回起動時にキャッシュを削除する 的本地化字符串。
        /// </summary>
        public static string StartContent_ClearCacheCheckBox {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「提督業も忙しい！」は、艦これを遊びやすくするためのツールです。 的本地化字符串。
        /// </summary>
        public static string StartContent_Introduction1 {
            get {
                return ResourceManager.GetString("StartContent_Introduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ようこそ 的本地化字符串。
        /// </summary>
        public static string StartContent_Welcom {
            get {
                return ResourceManager.GetString("StartContent_Welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦これの起動を待っています 的本地化字符串。
        /// </summary>
        public static string StatusBar_NotStarted {
            get {
                return ResourceManager.GetString("StatusBar_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 準備完了 的本地化字符串。
        /// </summary>
        public static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ツール 的本地化字符串。
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ズーム {0} % はサポートされていません。 的本地化字符串。
        /// </summary>
        public static string ZoomAction_OutOfRange {
            get {
                return ResourceManager.GetString("ZoomAction_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ズームに失敗しました: {0} 的本地化字符串。
        /// </summary>
        public static string ZoomAction_ZoomFailed {
            get {
                return ResourceManager.GetString("ZoomAction_ZoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ゲーム画面の表示サイズ 的本地化字符串。
        /// </summary>
        public static string ZoomFactorSelector {
            get {
                return ResourceManager.GetString("ZoomFactorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ゲーム画面の表示サイズを調整 的本地化字符串。
        /// </summary>
        public static string ZoomFactorSelector_Tooltip {
            get {
                return ResourceManager.GetString("ZoomFactorSelector_Tooltip", resourceCulture);
            }
        }
    }
}
