//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   明石が20分を修理しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Akashi_NotificationMessage {
            get {
                return ResourceManager.GetString("Akashi_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※近日実装予定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Implement_Oncoming {
            get {
                return ResourceManager.GetString("Common_Implement_Oncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知しない과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Notifications_Disable {
            get {
                return ResourceManager.GetString("Common_Notifications_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (未実装)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Notifications_NotImplemented {
            get {
                return ResourceManager.GetString("Common_Notifications_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知設定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Notifications_Title {
            get {
                return ResourceManager.GetString("Common_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Windows 8 以降)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Notifications_Windows8 {
            get {
                return ResourceManager.GetString("Common_Notifications_Windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦娘과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_ShipGirl {
            get {
                return ResourceManager.GetString("Common_ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これはテスト通知です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Debug_NotificationMessage {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Debug_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造ドック과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard {
            get {
                return ResourceManager.GetString("Dockyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成！과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Complete {
            get {
                return ResourceManager.GetString("Dockyard_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造中の艦名をネタバレする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Display_Reveal {
            get {
                return ResourceManager.GetString("Dockyard_Display_Reveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示設定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Display_Title {
            get {
                return ResourceManager.GetString("Dockyard_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックされています과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Locked {
            get {
                return ResourceManager.GetString("Dockyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工廠第 {0} ドックでの{1}の建造が完了しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造完了과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造完了時に通知を表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドックごとに個別に設定する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造中の艦과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_ShipName {
            get {
                return ResourceManager.GetString("Dockyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成時刻과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_TimeComplete {
            get {
                return ResourceManager.GetString("Dockyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造完了まで과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Dockyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未使用과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Unused {
            get {
                return ResourceManager.GetString("Dockyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征に出ていません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_NoExpedition {
            get {
                return ResourceManager.GetString("Expedition_NoExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」が遠征から帰投しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_NotificationMessage {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征完了과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征帰投時に通知を表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_Notifications_Enable {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊ごとに個別に設定する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_Notifications_Individual {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了時刻과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_TimeComplete {
            get {
                return ResourceManager.GetString("Expedition_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊帰投まで과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制空戦力과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fleets_AirSuperiorityPotential {
            get {
                return ResourceManager.GetString("Fleets_AirSuperiorityPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平均과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fleets_Average {
            get {
                return ResourceManager.GetString("Fleets_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レベル과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fleets_Level {
            get {
                return ResourceManager.GetString("Fleets_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速艦隊과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fleets_Speed_Fast {
            get {
                return ResourceManager.GetString("Fleets_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   低速艦隊과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fleets_Speed_Slow {
            get {
                return ResourceManager.GetString("Fleets_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fleets_Total {
            get {
                return ResourceManager.GetString("Fleets_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索敵能力과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fleets_ViewRange {
            get {
                return ResourceManager.GetString("Fleets_ViewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   司令部과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_FleetHQ {
            get {
                return ResourceManager.GetString("Homeport_FleetHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速建造材:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_InstantBuild {
            get {
                return ResourceManager.GetString("Homeport_InstantBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速修復材:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_InstantRepair {
            get {
                return ResourceManager.GetString("Homeport_InstantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保有装備:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_NoOfEquipment {
            get {
                return ResourceManager.GetString("Homeport_NoOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所属艦娘:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_NoOfShips {
            get {
                return ResourceManager.GetString("Homeport_NoOfShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総合과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IntegratedView {
            get {
                return ResourceManager.GetString("IntegratedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この艦隊は遠征中です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_Expedition {
            get {
                return ResourceManager.GetString("MessageBar_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    完了時刻:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_Expedition_TimeCompletion {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    帰投まで:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に入渠中の艦娘がいます。 完了時刻: {0:MM/dd HH\:mm} 完了まで: {1}:{2:mm\:ss}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_Repairing {
            get {
                return ResourceManager.GetString("MessageBar_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に入渠中の艦娘がいます。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_Repairing_Null {
            get {
                return ResourceManager.GetString("MessageBar_Repairing_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   疲労中の艦娘과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_ReSortie_BadCondition {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_BadCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に{0}がいます。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_ReSortie_CanNotReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanNotReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出撃可能！과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_ReSortie_CanReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未補給の艦娘과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_ReSortie_LackForResources {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_LackForResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再出撃までの目安: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_ReSortie_Remaining {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_ReSortie_Separator {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中破以上の艦娘과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageBar_ReSortie_Wounded {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Wounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任務과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在遂行中の任務과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_CurrentQuestList {
            get {
                return ResourceManager.GetString("Quests_CurrentQuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デイリー任務과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_Daily {
            get {
                return ResourceManager.GetString("Quests_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※進捗状況 (50 %, 80 %) はゲーム内の表示と同じです。敵艦隊の撃破数や遠征の成功回数のカウント等は行っていません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_Notice {
            get {
                return ResourceManager.GetString("Quests_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム内で [任務 (クエスト)] 画面を開いて、任務一覧を取得してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_Untaken {
            get {
                return ResourceManager.GetString("Quests_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィークリー任務과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_Weekly {
            get {
                return ResourceManager.GetString("Quests_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠ドック과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard {
            get {
                return ResourceManager.GetString("Repairyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックされています과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_Locked {
            get {
                return ResourceManager.GetString("Repairyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠第 {0} ドックでの「{1}」の整備が完了しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整備完了과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整備完了時に通知を表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドックごとに個別に設定する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠中の艦과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_ShipName {
            get {
                return ResourceManager.GetString("Repairyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了時刻과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_TimeComplete {
            get {
                return ResourceManager.GetString("Repairyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整備完了まで과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Repairyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未使用과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reparyard_Unused {
            get {
                return ResourceManager.GetString("Reparyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」の全艦娘の疲労が回復しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReSortie_NotificationMessage {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   疲労回復完了과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReSortie_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットの保存に失敗しました: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Screenshot_Failed {
            get {
                return ResourceManager.GetString("Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットを保存しました: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Screenshot_Saved {
            get {
                return ResourceManager.GetString("Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザー操作과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_BrowserControl {
            get {
                return ResourceManager.GetString("Settings_BrowserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズーム倍率を 100 % に戻す과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_BrowserControl_ClearZoomFactorButton {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_ClearZoomFactorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (表示)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_BrowserControl_Display {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ゲームのページから移動します。ご注意ください과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_BrowserControl_Notice {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示設定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Display {
            get {
                return ResourceManager.GetString("Settings_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドロップ・建造・開発ログを記録する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Logging_Enable {
            get {
                return ResourceManager.GetString("Settings_Logging_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信設定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Network {
            get {
                return ResourceManager.GetString("Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作設定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Operation {
            get {
                return ResourceManager.GetString("Settings_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロキシ設定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy {
            get {
                return ResourceManager.GetString("Settings_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTTP 通信に指定のプロキシ サーバーを使用する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy_Enable {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSL 接続時もプロキシサーバーを使用する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy_Enable_4_SSL {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_4_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy_Host {
            get {
                return ResourceManager.GetString("Settings_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy_Port {
            get {
                return ResourceManager.GetString("Settings_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショット과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot {
            get {
                return ResourceManager.GetString("Settings_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_OpenButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットの保存先を指定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_Title {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先フォルダーのパス과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Prompt {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像形式과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_ImageFormat_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_ImageFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを開く과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_OpenFolderButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_VersionInfo {
            get {
                return ResourceManager.GetString("Settings_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ設定과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Window {
            get {
                return ResourceManager.GetString("Settings_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウを常に最前面に表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Window_TopMost {
            get {
                return ResourceManager.GetString("Settings_Window_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ操作과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_WindowControl {
            get {
                return ResourceManager.GetString("Settings_WindowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウをモニターの左端に寄せる과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8 インチタブレット (800 x 1280) 用과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton_Sub {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュの削除과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartContent_ClearCacheButton {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュを削除しました과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartContent_ClearCacheButtonMessage {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「提督業も忙しい！」は、艦これを遊びやすくするためのツールです。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartContent_Introduction1 {
            get {
                return ResourceManager.GetString("StartContent_Introduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ようこそ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartContent_Welcom {
            get {
                return ResourceManager.GetString("StartContent_Welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦これの起動を待っています과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusBar_NotStarted {
            get {
                return ResourceManager.GetString("StatusBar_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備完了과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズーム {0} % はサポートされていません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZoomAction_OutOfRange {
            get {
                return ResourceManager.GetString("ZoomAction_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズームに失敗しました: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZoomAction_ZoomFailed {
            get {
                return ResourceManager.GetString("ZoomAction_ZoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム画面の表示サイズ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZoomFactorSelector {
            get {
                return ResourceManager.GetString("ZoomFactorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム画面の表示サイズを調整과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZoomFactorSelector_Tooltip {
            get {
                return ResourceManager.GetString("ZoomFactorSelector_Tooltip", resourceCulture);
            }
        }
    }
}
