// 
// This file was generated by "KanColleProxy.Endpoints.tt"
// 

using Fiddler;
using System;
using System.Reactive.Linq;

namespace Grabacr07.KanColleWrapper
{
	partial class KanColleProxy
	{
		// ReSharper disable InconsistentNaming

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_start2" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_start2
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_start2"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_port/port" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_port
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_port/port"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/basic" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_basic
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/basic"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/ship" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_ship
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/ship"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/ship2" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_ship2
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/ship2"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/ship3" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_ship3
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/ship3"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/slot_item" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_slot_item
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/slot_item"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/useitem" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_useitem
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/useitem"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/deck" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_deck
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/deck"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/deck_port" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_deck_port
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/deck_port"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/ndock" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_ndock
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/ndock"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/kdock" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_kdock
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/kdock"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/material" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_material
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/material"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/questlist" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_questlist
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/questlist"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_hensei/change" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_hensei_change
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_hensei/change"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_hokyu/charge" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_hokyu_charge
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_hokyu/charge"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_kaisou/powerup" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_kaisou_powerup
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_kaisou/powerup"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_kousyou/getship" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_kousyou_getship
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_kousyou/getship"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_kousyou/createitem" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_kousyou_createitem
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_kousyou/createitem"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_kousyou/createship" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_kousyou_createship
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_kousyou/createship"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_kousyou/createship_speedchange" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_kousyou_createship_speedchange
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_kousyou/createship_speedchange"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_kousyou/destroyship" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_kousyou_destroyship
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_kousyou/destroyship"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_kousyou/destroyitem2" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_kousyou_destroyitem2
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_kousyou/destroyitem2"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_kousyou/remodel_slot" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_kousyou_remodel_slot
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_kousyou/remodel_slot"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_nyukyo/start" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_nyukyo_start
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_nyukyo/start"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_nyukyo/speedchange" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_nyukyo_speedchange
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_nyukyo/speedchange"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_map/start" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_map_start
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_map/start"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_member/updatedeckname" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_member_updatedeckname
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_member/updatedeckname"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_member/updatecomment" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_member_updatecomment
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_member/updatecomment"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_mission/result" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_mission_result
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_mission/result"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_sortie/battle" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_sortie_battle
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_sortie/battle"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_sortie/battleresult" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_sortie_battleresult
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_sortie/battleresult"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_battle_midnight/battle" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_battle_midnight_battle
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_battle_midnight/battle"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_battle_midnight/sp_midnight" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_battle_midnight_sp_midnight
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_battle_midnight/sp_midnight"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_sortie/night_to_day" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_sortie_night_to_day
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_sortie/night_to_day"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_hensei/combined" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_hensei_combined
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_hensei/combined"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_combined_battle/battle" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_combined_battle_battle
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_combined_battle/battle"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_combined_battle/midnight_battle" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_combined_battle_midnight_battle
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_combined_battle/midnight_battle"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_combined_battle/airbattle" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_combined_battle_airbattle
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_combined_battle/airbattle"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_combined_battle/battleresult" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_combined_battle_battleresult
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_combined_battle/battleresult"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_req_combined_battle/battle_water" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_req_combined_battle_battle_water
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_req_combined_battle/battle_water"); }
		}

		/// <summary>
		/// 엔드포인트 "/kcsapi/api_get_member/mapinfo" 에서 세션을 제공합니다.
		/// </summary>
		public IObservable<Session> api_get_member_mapinfo
		{
			get { return this.ApiSessionSource.Where(x => x.PathAndQuery == "/kcsapi/api_get_member/mapinfo"); }
		}

		// ReSharper restore InconsistentNaming
	}
}
