//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34003
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ※ To be implemented과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Implement_Oncoming {
            get {
                return ResourceManager.GetString("Common_Implement_Oncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Notifications_Disable {
            get {
                return ResourceManager.GetString("Common_Notifications_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (planned)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Notifications_NotImplemented {
            get {
                return ResourceManager.GetString("Common_Notifications_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Notifications_Title {
            get {
                return ResourceManager.GetString("Common_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Windows 8+)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Notifications_Windows8 {
            get {
                return ResourceManager.GetString("Common_Notifications_Windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shipgirl과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_ShipGirl {
            get {
                return ResourceManager.GetString("Common_ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Construction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard {
            get {
                return ResourceManager.GetString("Dockyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Complete {
            get {
                return ResourceManager.GetString("Dockyard_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reveal Ship Names과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Display_Reveal {
            get {
                return ResourceManager.GetString("Dockyard_Display_Reveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Display_Title {
            get {
                return ResourceManager.GetString("Dockyard_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Locked {
            get {
                return ResourceManager.GetString("Dockyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Construction of {1} in Dock {0} has been completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Construction Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify Upon Completion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Individual Dock Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ship In Progress과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_ShipName {
            get {
                return ResourceManager.GetString("Dockyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completion Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_TimeComplete {
            get {
                return ResourceManager.GetString("Dockyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remaining Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Dockyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dockyard_Unused {
            get {
                return ResourceManager.GetString("Dockyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expeditions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not on an Expedition.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_NoExpedition {
            get {
                return ResourceManager.GetString("Expedition_NoExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」 has returned from an expedition.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_NotificationMessage {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expedition Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify Upon Completion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_Notifications_Enable {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Individual Fleet Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_Notifications_Individual {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completion Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_TimeComplete {
            get {
                return ResourceManager.GetString("Expedition_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remaining Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fleets과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fleet HQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_FleetHQ {
            get {
                return ResourceManager.GetString("Homeport_FleetHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instant Build Materials:  과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_InstantBuild {
            get {
                return ResourceManager.GetString("Homeport_InstantBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instant Repair Materials:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_InstantRepair {
            get {
                return ResourceManager.GetString("Homeport_InstantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_NoOfEquipment {
            get {
                return ResourceManager.GetString("Homeport_NoOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ship Girls:  과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Homeport_NoOfShips {
            get {
                return ResourceManager.GetString("Homeport_NoOfShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IntegratedView {
            get {
                return ResourceManager.GetString("IntegratedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please visit all of the quest pages.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quest_Detail_Untaken {
            get {
                return ResourceManager.GetString("Quest_Detail_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    50% 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quest_Progress_50 {
            get {
                return ResourceManager.GetString("Quest_Progress_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///    80% 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quest_Progress_80 {
            get {
                return ResourceManager.GetString("Quest_Progress_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Complete 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quest_State_Accomplished {
            get {
                return ResourceManager.GetString("Quest_State_Accomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Unknown quest)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quest_Title_Untaken {
            get {
                return ResourceManager.GetString("Quest_Title_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quests과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active Quests과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_CurrentQuestList {
            get {
                return ResourceManager.GetString("Quests_CurrentQuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily Quests과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_Daily {
            get {
                return ResourceManager.GetString("Quests_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ The indicators (50%, 80%) mirror in-game indicators. Enemy fleet kills, successful expeditions, etc are not actively counted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_Notice {
            get {
                return ResourceManager.GetString("Quests_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please open the in-game Quests menu to populate the Quest list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_Untaken {
            get {
                return ResourceManager.GetString("Quests_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weekly Quests과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_Weekly {
            get {
                return ResourceManager.GetString("Quests_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repair과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard {
            get {
                return ResourceManager.GetString("Repairyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_Locked {
            get {
                return ResourceManager.GetString("Repairyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repairs on {1} in Dock {0} have been completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repairs Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify Upon Completion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Individual Dock Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Docked Ship과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_ShipName {
            get {
                return ResourceManager.GetString("Repairyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completion Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_TimeComplete {
            get {
                return ResourceManager.GetString("Repairyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remaining Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Repairyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Repairyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reparyard_Unused {
            get {
                return ResourceManager.GetString("Reparyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All ships in 「{0}」 have fully recovered from fatigue.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReSortie_NotificationMessage {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatigue Recovery Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReSortie_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screenshot save failed: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Screenshot_Failed {
            get {
                return ResourceManager.GetString("Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screenshot saved: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Screenshot_Saved {
            get {
                return ResourceManager.GetString("Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_BrowserControl {
            get {
                return ResourceManager.GetString("Settings_BrowserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset zoom to 100%과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_BrowserControl_ClearZoomFactorButton {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_ClearZoomFactorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Display)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_BrowserControl_Display {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ This will leave the game, so use with caution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_BrowserControl_Notice {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Display {
            get {
                return ResourceManager.GetString("Settings_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Network {
            get {
                return ResourceManager.GetString("Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Behaviour과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Operation {
            get {
                return ResourceManager.GetString("Settings_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proxy Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy {
            get {
                return ResourceManager.GetString("Settings_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use a proxy to connect the server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy_Enable {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use the proxy for SSL connections과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy_Enable_4_SSL {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_4_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy_Host {
            get {
                return ResourceManager.GetString("Settings_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Proxy_Port {
            get {
                return ResourceManager.GetString("Settings_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screenshot Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot {
            get {
                return ResourceManager.GetString("Settings_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_OpenButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a location to save screenshots과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_Title {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination Folder Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Prompt {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_ImageFormat_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_ImageFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Screenshot_OpenFolderButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_VersionInfo {
            get {
                return ResourceManager.GetString("Settings_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Window {
            get {
                return ResourceManager.GetString("Settings_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep window on top과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Window_TopMost {
            get {
                return ResourceManager.GetString("Settings_Window_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Controls과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_WindowControl {
            get {
                return ResourceManager.GetString("Settings_WindowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dock window to left of screen.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For use with 8 inch tablets (800x1280)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton_Sub {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Air Superiority Potential:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusBar_AirSuperiorityPotential {
            get {
                return ResourceManager.GetString("StatusBar_AirSuperiorityPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average Level:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusBar_AverageLevel {
            get {
                return ResourceManager.GetString("StatusBar_AverageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for KanColle to start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusBar_NotStarted {
            get {
                return ResourceManager.GetString("StatusBar_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast Fleet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusBar_Speed_Fast {
            get {
                return ResourceManager.GetString("StatusBar_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slow Fleet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusBar_Speed_Slow {
            get {
                return ResourceManager.GetString("StatusBar_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}% zoom is not supported.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZoomAction_OutOfRange {
            get {
                return ResourceManager.GetString("ZoomAction_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Failed: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZoomAction_ZoomFailed {
            get {
                return ResourceManager.GetString("ZoomAction_ZoomFailed", resourceCulture);
            }
        }
    }
}
