//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AudibleNotificationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AudibleNotificationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Plugins.Properties.AudibleNotificationsResources", typeof(AudibleNotificationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse….
        /// </summary>
        public static string Settings_Browse {
            get {
                return ResourceManager.GetString("Settings_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folders.
        /// </summary>
        public static string Settings_CreateFolders_Button {
            get {
                return ResourceManager.GetString("Settings_CreateFolders_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will create sub-folders for the currently enabled notification types. Please be aware that if no folder is found for a particular type, or the folder does not have any MPEG II Layer 3 (.mp3) or RIFF WAVE (.wav) audio files, default audio will be used..
        /// </summary>
        public static string Settings_CreateFolders_Description {
            get {
                return ResourceManager.GetString("Settings_CreateFolders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sub-folders.
        /// </summary>
        public static string Settings_CreateFolders_Title {
            get {
                return ResourceManager.GetString("Settings_CreateFolders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※ To create sub-folders: see below..
        /// </summary>
        public static string Settings_Hint {
            get {
                return ResourceManager.GetString("Settings_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Settings_Location {
            get {
                return ResourceManager.GetString("Settings_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string Settings_OpenFolder {
            get {
                return ResourceManager.GetString("Settings_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible alerts will be enabled for the following notifications:.
        /// </summary>
        public static string Settings_Types_Description {
            get {
                return ResourceManager.GetString("Settings_Types_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※ This list only includes notification types defined in the Notification.Types class. For other notification types default audio will be used..
        /// </summary>
        public static string Settings_Types_Footnote {
            get {
                return ResourceManager.GetString("Settings_Types_Footnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Types.
        /// </summary>
        public static string Settings_Types_Title {
            get {
                return ResourceManager.GetString("Settings_Types_Title", resourceCulture);
            }
        }
    }
}
