//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse….
        /// </summary>
        public static string Settings_Browse {
            get {
                return ResourceManager.GetString("Settings_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string Settings_GeneralSettings_Title {
            get {
                return ResourceManager.GetString("Settings_GeneralSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Settings_Location {
            get {
                return ResourceManager.GetString("Settings_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Format.
        /// </summary>
        public static string Settings_LogFormat {
            get {
                return ResourceManager.GetString("Settings_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Settings_LoggerEnable {
            get {
                return ResourceManager.GetString("Settings_LoggerEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample log line:.
        /// </summary>
        public static string Settings_LogSample {
            get {
                return ResourceManager.GetString("Settings_LogSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string Settings_OpenFolder {
            get {
                return ResourceManager.GetString("Settings_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time format.
        /// </summary>
        public static string Settings_TimestampFormat {
            get {
                return ResourceManager.GetString("Settings_TimestampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※ More information:.
        /// </summary>
        public static string Settings_TimestampFormat_Description {
            get {
                return ResourceManager.GetString("Settings_TimestampFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx.
        /// </summary>
        public static string Settings_TimestampFormat_URI {
            get {
                return ResourceManager.GetString("Settings_TimestampFormat_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date/time format strings.
        /// </summary>
        public static string Settings_TimestampFormat_URI_Description {
            get {
                return ResourceManager.GetString("Settings_TimestampFormat_URI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: ISO timestamp (UTC)
        ///{1}: Timestamp (local time or JST)
        ///{2}: Drop name
        ///{3}: Map name
        ///{4}: Map node name
        ///{5}: Victory rank.
        /// </summary>
        public static string Settings_Tooltip_BattleResult {
            get {
                return ResourceManager.GetString("Settings_Tooltip_BattleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: ISO timestamp (UTC)
        ///{1}: Timestamp (local time or JST)
        ///{2}: Result
        ///{3}: Fuel
        ///{4}: Ammo
        ///{5}: Steel
        ///{6}: Bauxite
        ///{7}: Secretary name
        ///{8}: Secretary hull code.
        /// </summary>
        public static string Settings_Tooltip_Construction {
            get {
                return ResourceManager.GetString("Settings_Tooltip_Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: ISO timestamp (UTC)
        ///{1}: Timestamp (local time or JST)
        ///{2}: Result
        ///{3}: Secretary class
        ///{4}: Fuel
        ///{5}: Ammo
        ///{6}: Steel
        ///{7}: Bauxite
        ///{8}: Secretary hull code.
        /// </summary>
        public static string Settings_Tooltip_Development {
            get {
                return ResourceManager.GetString("Settings_Tooltip_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: ISO timestamp (UTC)
        ///{1}: Timestamp (local time or JST)
        ///{2}: Fuel
        ///{3}: Ammo
        ///{4}: Steel
        ///{5}: Bauxite
        ///{6}: Development kits
        ///{7}: Instant repair
        ///{8}: Instant construction
        ///{9}: Improvement materials.
        /// </summary>
        public static string Settings_Tooltip_Materials {
            get {
                return ResourceManager.GetString("Settings_Tooltip_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Japanese Standard Time (UTC+0900).
        /// </summary>
        public static string Settings_UseJST {
            get {
                return ResourceManager.GetString("Settings_UseJST", resourceCulture);
            }
        }
    }
}
